### ISSUE TITLE
Cannot use Top or Bot in type declarations

### ISSUE THREAD

**Issue by klauso** [duo-lang/duo-lang#307]
DualSub Version: f5bd4ebdccf5f510c3c43d65ccc523be65d9df34

The following declaration
```
data P :  CBN {
    Q(Top)
}; 
```
yields the error `Cannot use Top in positive polarity`. The dual error occurs when using `Bot`.

**Comment by BinderDavid** [comment]
Added this restriction to the documentation: https://github.com/duo-lang/documentation/pull/1
